app/models.py
from app import db, login
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref="author", lazy="dynamic")

    def set_password(self, password: str):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    @login.user_loader
    def load_user(id: str):
        return User.query.get(int(id))


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    title = db.Column(db.String(128), index=True)
    description = db.Column(db.String(512), index=True)
    file_path = db.Column(db.String(256))
    likes = db.relationship('PostLikes', backref="liked", lazy="dynamic")

    def like_amount(self):
        return self.likes.count()

    def do_user_like(self, user_id: int):
        return self.likes.filter_by(user_id=user_id).first() is not None


class PostLikes(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))
    user_id = db.Column(db.Integer)

    def do_user_like(self, id: int):
        return self.user_id == id

app/dashboard/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired
from wtforms import StringField, FileField, SubmitField
from wtforms.validators import DataRequired


class PostingForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    file = FileField('File', validators=[FileRequired()])
    submit = SubmitField('Send')

app/__init__.py
import os.path

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from config import Config

db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()
login = LoginManager()


def create_app(config=Config):
    app = Flask(__name__, static_folder='../static')
    app.config.from_object(config)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.dashboard import bp as dashboard_bp
    app.register_blueprint(dashboard_bp, url_prefix='')

    return app

app/dashboard/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard', __name__)

from app.dashboard import routes

app/dashboard/routes.py
import os
from flask import render_template, request, flash, url_for
from app import db
from app.dashboard import bp
from app.models import Post, PostLikes
from flask_login import login_required, current_user
from app.dashboard.forms import PostingForm
from werkzeug.utils import secure_filename, redirect


@bp.route('/', methods=["GET", "POST"])
@login_required
def index():
    form = PostingForm()
    posts = Post.query.filter_by(user_id=current_user.get_id()).all()
    if form.validate_on_submit():
        file = request.files['file']
        file_name = secure_filename(file.filename)
        user_id = current_user.get_id()
        path = os.path.join('static/images', current_user.get_id())
        if not os.path.exists(path):
            os.makedirs(path)
        file_path = os.path.join(path, file_name)
        post = Post(user_id=user_id, title=form.title.data, description=form.description.data, file_path=file_path)
        db.session.add(post)
        db.session.commit()
        file.save(file_path)
        flash("You have successfully added a post!")
        return redirect(url_for('dashboard.index'))
    return render_template('dashboard/index.html', form=form, posts=posts)


@bp.route('/explore', methods=["GET", "POST"])
@login_required
def explore():
    posts = Post.query.filter(Post.user_id != current_user.id).all()
    return render_template('dashboard/explore.html', posts=posts)


@bp.route('/posts/remove/<int:id>')
@login_required
def remove_post(id: int):
    post = Post.query.filter_by(id=id).first()
    PostLikes.query.filter_by(post_id=id).delete()
    if post is not None:
        db.session.delete(post)
        db.session.commit()
    return redirect(url_for('dashboard.index'))


@bp.route('/posts/like/<int:id>')
@login_required
def like_post(id: int):
    post = Post.query.filter_by(id=id).first()
    if post is not None:
        post_like = PostLikes(post_id=post.id, user_id=current_user.get_id())
        db.session.add(post_like)
        db.session.commit()
    return redirect(url_for('dashboard.explore'))


@bp.route('/posts/dislike/<int:id>')
@login_required
def dislike_post(id: int):
    post_like = PostLikes.query.filter_by(post_id=id, user_id=current_user.get_id()).first()
    if post_like is not None:
        db.session.delete(post_like)
        db.session.commit()
    return redirect(url_for('dashboard.explore'))

app/templates/_post.html
<ul class="list-group">
  <li class="list-group-item">
      <div class="row">
        <div class="col-md-2">
            <h3 class="display-6">
                {{ post.title }}
            </h3>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
            <span>Likes: {{ post.like_amount() }}</span>
            {% if current_user.id == post.user_id %}
                <button onclick="window.location.href='{{ url_for('dashboard.remove_post', id=post.id) }}';" class="btn btn-danger">
                    X
                </button>
            {% else %}
                {% if post.do_user_like(current_user.get_id()) %}
                    <button onclick="window.location.href='{{ url_for('dashboard.dislike_post', id=post.id) }}';" class="btn btn-danger">
                        Dislike
                    </button>
                {% else %}
                    <button onclick="window.location.href='{{ url_for('dashboard.like_post', id=post.id) }}';" class="btn btn-primary">
                        Like
                    </button>
                {% endif %}
            {% endif %}
        </div>
      </div>
  </li>
  <li class="list-group-item">{{ post.description }}</li>
  <li class="list-group-item">
      <img class="img-responsive" src="{{ post.file_path }}" alt="photo">
  </li>
</ul>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
    <nav class="navbar sticky-top navbar-light" style="background-color: #e3f2fd;">
        <ul class="navbar-nav mr-auto">
            <a class="navbar-brand" href="{{ url_for('dashboard.index') }}">Home</a>
        </ul>

        <ul class="navbar-nav ml-5">
            {% if current_user.is_anonymous %}
                <a class="navbar-brand" href="{{ url_for('auth.login') }}">Login</a>
            {% else %}
                <a class="navbar-brand" href="{{ url_for('dashboard.explore') }}">Explore</a>
                <a class="navbar-brand" href="{{ url_for('auth.logout') }}">Logout</a>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container container-sm">
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/dashboard/explore.html
{% extends 'base.html' %}


{% block app_content %}
    <h1 class="display-4">
        Explore other people posts!
    </h1>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
{% endblock %}

app/templates/dashboard/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block app_content %}
    <h1 class="display-4">
        Welcome <span style="color:#444;">{{ current_user.username }}</span> to your dashboard!
    </h1>
    <div class="row">
        <div class="col-md-4">
            <h2 class="display-6">
                Post something cool!
            </h2>
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
{% endblock %}